name: workflow
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
    integration:
        name: CI
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Lint the code
              run: echo "linting the code"
            - name: Run unit tests
              run: echo "running unit tests" 